import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import "./rootlayout.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ThemeProvider from "./theme-provider";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
